//
//  Lexicon.swift
//  MongolEngine
//
//  The word lexicon behind pinyin-style candidate suggestions: real
//  traditional-script (mongol bichig) spellings of ~28k Mongolian words,
//  indexed by the folded romanization of their MODERN pronunciation. This is
//  what lets a user type `mongol` and get the orthographically correct
//  ᠮᠣᠩᠭᠣᠯ, which no letter-by-letter transliteration can produce.
//
//  Data: Resources/lexicon.tsv, generated by tools/generate_lexicon.py from
//  the MIT-licensed `written-mongol-keyboard` dictionary, ranked with the
//  tugstugi/mongolian-nlp news-corpus frequency list. See the script header
//  for provenance and cleaning rules.
//

import Foundation

public struct Lexicon {

    /// One candidate word: a lookup key (folded romanization), the correct
    /// traditional-script spelling, the Cyrillic form (shown as a caption so
    /// the user can confirm which word they are picking), and a corpus
    /// frequency (0 when the word is not in the top-frequency list).
    public struct Entry: Equatable {
        public let key: String
        public let traditional: String
        public let cyrillic: String
        public let frequency: Int

        public init(key: String, traditional: String, cyrillic: String, frequency: Int) {
            self.key = key
            self.traditional = traditional
            self.cyrillic = cyrillic
            self.frequency = frequency
        }
    }

    /// All entries, sorted by `key` (the TSV is generated pre-sorted; the
    /// designated initializer re-sorts, so the invariant always holds).
    public let entries: [Entry]

    /// The shared lexicon, loaded once from the package resource bundle.
    /// First access parses the TSV (~30k lines); the keyboard warms this on a
    /// background queue at launch so typing never waits for it.
    public static let shared = Lexicon(bundle: .module)

    public init(entries: [Entry]) {
        self.entries = entries.sorted { $0.key < $1.key }
    }

    /// Load from `lexicon.tsv` in `bundle`. A missing or unreadable resource
    /// yields an empty lexicon — the keyboard then degrades to plain
    /// transliteration instead of failing.
    public init(bundle: Bundle) {
        guard let url = bundle.url(forResource: "lexicon", withExtension: "tsv"),
              let raw = try? String(contentsOf: url, encoding: .utf8) else {
            self.entries = []
            return
        }
        var parsed: [Entry] = []
        parsed.reserveCapacity(30_000)
        for line in raw.split(separator: "\n") {
            let cols = line.split(separator: "\t", omittingEmptySubsequences: false)
            guard cols.count == 4 else { continue }
            parsed.append(Entry(key: String(cols[0]),
                                traditional: String(cols[1]),
                                cyrillic: String(cols[2]),
                                frequency: Int(cols[3]) ?? 0))
        }
        self.init(entries: parsed)
    }

    public var isEmpty: Bool { entries.isEmpty }
    public var count: Int { entries.count }

    // MARK: Lookup

    /// All words whose folded romanization equals `key` (homophones — the
    /// same pronunciation can have several traditional spellings).
    public func exactMatches(forKey key: String) -> [Entry] {
        guard !key.isEmpty else { return [] }
        var i = lowerBound(of: key)
        var result: [Entry] = []
        while i < entries.count && entries[i].key == key {
            result.append(entries[i])
            i += 1
        }
        return result
    }

    /// All words whose key strictly extends `prefix` (exact matches excluded).
    public func completions(forKeyPrefix prefix: String) -> [Entry] {
        guard !prefix.isEmpty else { return [] }
        var i = lowerBound(of: prefix)
        var result: [Entry] = []
        while i < entries.count && entries[i].key.hasPrefix(prefix) {
            if entries[i].key != prefix {
                result.append(entries[i])
            }
            i += 1
        }
        return result
    }

    /// Index of the first entry whose key is >= `key` (binary search).
    private func lowerBound(of key: String) -> Int {
        var lo = 0
        var hi = entries.count
        while lo < hi {
            let mid = (lo + hi) / 2
            if entries[mid].key < key {
                lo = mid + 1
            } else {
                hi = mid
            }
        }
        return lo
    }
}
