//
//  Predictor.swift
//  MongolEngine
//
//  Next-word prediction, the way people actually write: after a word is
//  committed, the words that most often follow it are offered in the bar.
//  Data: Resources/bigrams.tsv — word-pair counts from 23.7M words of
//  Mongolian news (Eduge) plus 79k lines of song lyrics, generated by
//  tools/generate_lexicon.py. Each next word is stored with its
//  dictionary-verified traditional spelling, so a prediction is never a
//  transliteration guess.
//

import Foundation

public struct Predictor {

    /// One predicted next word.
    public struct Prediction: Equatable {
        public let mongolian: String
        public let cyrillic: String
        /// How often the pair occurred in the corpora.
        public let count: Int

        public init(mongolian: String, cyrillic: String, count: Int) {
            self.mongolian = mongolian
            self.cyrillic = cyrillic
            self.count = count
        }
    }

    private struct Row {
        let head: String
        let prediction: Prediction
    }

    /// Sorted by `head` (the Cyrillic form of the previous word), then by
    /// count descending — the table is generated in that order.
    private let rows: [Row]

    /// The shared table, loaded once from the package resource bundle.
    public static let shared = Predictor(bundle: .module)

    public init(rows: [(head: String, prediction: Prediction)]) {
        self.rows = rows
            .map { Row(head: $0.head, prediction: $0.prediction) }
            .sorted { a, b in
                if a.head != b.head { return a.head < b.head }
                return a.prediction.count > b.prediction.count
            }
    }

    /// Load from `bigrams.tsv` in `bundle`. A missing resource yields an
    /// empty predictor — the keyboard then simply shows no predictions.
    public init(bundle: Bundle) {
        guard let url = bundle.url(forResource: "bigrams", withExtension: "tsv"),
              let raw = try? String(contentsOf: url, encoding: .utf8) else {
            self.init(rows: [])
            return
        }
        var parsed: [(head: String, prediction: Prediction)] = []
        parsed.reserveCapacity(30_000)
        for line in raw.split(separator: "\n") {
            let cols = line.split(separator: "\t", omittingEmptySubsequences: false)
            guard cols.count == 4 else { continue }
            parsed.append((head: String(cols[0]),
                           prediction: Prediction(mongolian: String(cols[1]),
                                                  cyrillic: String(cols[2]),
                                                  count: Int(cols[3]) ?? 0)))
        }
        self.init(rows: parsed)
    }

    public var isEmpty: Bool { rows.isEmpty }
    public var count: Int { rows.count }

    /// The most likely next words after `previous` (its Cyrillic form),
    /// most frequent first.
    public func successors(of previous: String, limit: Int = 3) -> [Prediction] {
        guard !previous.isEmpty, limit > 0 else { return [] }
        var i = lowerBound(of: previous)
        var result: [Prediction] = []
        while i < rows.count && rows[i].head == previous && result.count < limit {
            result.append(rows[i].prediction)
            i += 1
        }
        return result
    }

    /// Cyrillic forms of every stored successor of `previous` — used to
    /// rank candidates by context while the next word is being typed.
    public func successorSet(of previous: String) -> Set<String> {
        Set(successors(of: previous, limit: Int.max).map { $0.cyrillic })
    }

    private func lowerBound(of head: String) -> Int {
        var lo = 0
        var hi = rows.count
        while lo < hi {
            let mid = (lo + hi) / 2
            if rows[mid].head < head { lo = mid + 1 } else { hi = mid }
        }
        return lo
    }
}
